---
- hosts: webservers 
  become: yes
  become_method: sudo
  vars:
    packages: [ 'vim', 'git', 'curl' ]
  tasks:
  - name: Install Package
    apt: name={{ item }} state=latest
    with_items: packages