---
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root
  vars:
    packages: [vim, git, curl]
  tasks:
  - name: Ping Servers
    ping:
  - name: Debug - print variables
    debug: 
      var: packages    
  - name: Install Package    
    apt: name={{ item }} state=latest
    with_items: 
      - "{{ packages  }}"
