---
- hosts: webservers
  become: enable
  become_method: sudo
  become_user: root
  vars:
    packages: [vim, git, curl]
  tasks:
  - name: Ping Servers
    ping:
  - name: Debug - print variables
    debug: 
      msg: "{{ packages }}" 
    ping:
  - name: Install Package    
    apt: name={{ item }} state=latest
    with_items: 
      - "{{ packages  }}"
