---
- hosts: webservers
  become: enable
  become_method: sudo
  become_user: root
  vars:
    packages: [ 'vim', 'git', 'curl' ]
  tasks:
  - name: Install Package
    debug: 
      msg: "{{ item }}"
    apt: name={{ item }} state=latest
    with_items: 
      - "{{ packages  }}"
