---
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Chenking ping
    ping:
  - name: Install apache2
    apt:
      name: apache2
      update_cache: true
      state: latest
  - name: Copy index.html to /var/www/html
    copy:
      src: /home/vladimir/Documents/ansible/playbooks/index.html
      dest: /var/www/html
      owner: vladimir
      group: vladimir
      mode: u+rw,g+rw,o+rw
  - name: Restart apache2
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: install php module
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
  - name: Install MySQL DB server
    apt:
      name: mysql-server
      state: latest
 
