---
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Chenking ping
    ping:
  - name: Install apache2
    apt:
      name: apache2
      update_cache: true
      state: latest
  - name: Copy index.html to /var/www/html
    copy:
      src: /home/vladimir/ansible/AnsibleCourse/playbooks/index.html
      dest: /var/www/html
      owner: vladimir
      group: vladimir
      mode: u+rw,g+rw,o+rw
  - name: Restart apache2
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: "Update Repository cache"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
  - name: install php module
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - php
     - libapache2-mod-php
       # - php-mcrypt
     - php-mysql
