---
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root
  - name: Install apache2
    apt:
      name: apache2
      update_cache: true
      state: latest
  - name: Restart apache2
    service:
      name: apache2
      enabled: yes
      state: restarted


